### ISSUE TITLE
5.3.0.5 doesn't build

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-session-ui#170]
```
In file included from unittest.cpp:22:
unittest.h:26:10: fatal error: QtTest: No such file or directory
   26 | #include <QtTest>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1223: unittest.o] Error 1
```

Offending commit: https://github.com/linuxdeepin/dde-session-ui/commit/bbfc0f99d67853a1c0d72959144e5112dc59480d#diff-efc3bd923a0ba7f492ee564c487005e4

**Comment by xmuli** [comment]
@justforlxz

**Comment by felixonmars** [comment]
Seems fixed in 5.3.0.23 (most probably earlier). Closing.
